version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Instalando dependências..."
      - pip install -r app/requirements.txt
  build:
    commands:
      - echo "Executando testes unitários..."
      - export PYTHONPATH=app
      - pytest app/test_app.py
artifacts:
  files:
    - '**/*'
