version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Instalando dependências..."
      - pip install -r app/requirements.txt
      - pip install pytest jsonschema
  build:
    commands:
      - echo "========== INICIANDO TESTES =========="
      - export PYTHONPATH=app

      - echo "🔹 Executando testes unitários..."
      - pytest app/test_app.py 

      - echo "🔹 Executando testes de integração..."
      - pytest app/test_integracao.py

      - echo "🔹 Executando testes de contrato..."
      - pytest app/test_contrato.py

      - echo "🔹 Executando testes de validação de erro..."
      - pytest app/test_erros.py

      - echo "🔹 Executando testes de vunerabildiade de codigo pyhton"
      - bandit -r app/ || true  
      - echo "✅ Todos os testes foram executados."
artifacts:
  files:
    - '**/*'

